# Generated by Django 4.1.3 on 2023-02-26 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import foodservice.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('store_picture', models.FileField(upload_to=foodservice.models.handle_store_picture)),
                ('location', models.TextField()),
                ('phonenumber', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^[\\+]?[(]?[0-9]{3}[)]?[-\\s\\.]?[0-9]{3}[-\\s\\.]?[0-9]{4,7}$')])),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
