# Generated by Django 4.1.3 on 2023-03-11 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodservice',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='foodservice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foodservice', to=settings.AUTH_USER_MODEL),
        ),
    ]
