# Generated by Django 4.1.3 on 2023-03-01 20:52

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='face',
            field=models.ImageField(default=1, upload_to=account.models.Account.upload_face_image),
            preserve_default=False,
        ),
    ]
