# Generated by Django 4.1.3 on 2023-03-11 15:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.Account.upload_face_image),
        ),
    ]
