# Generated by Django 4.1.3 on 2023-03-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodservice', '0002_remove_foodservice_phonenumber_and_more'),
        ('product', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'foodservice')},
        ),
    ]
