# Generated by Django 4.1.3 on 2023-04-15 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0004_alter_order_options_alter_item_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('pickup_status', models.CharField(choices=[['pending', 'Pending'], ['success', 'Success'], ['failed', 'Failed']], default='pending', max_length=7)),
                ('delivery_status', models.CharField(choices=[['pending', 'Pending'], ['success', 'Success'], ['failed', 'Failed']], default='pending', max_length=7)),
                ('pay', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
