# Generated by Django 4.1.3 on 2023-04-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_alter_courierorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courierorder',
            name='pickup_status',
        ),
    ]
